run smaller spec test and upload all resulting files

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -556,7 +556,7 @@ stages:
                 pwd
                 ls -l .
                 $Env:PERL_TEST_HARNESS_DUMP_TAP = "test_results"
-                prove --formatter TAP::Formatter::JUnit -e ..\install\bin\raku -vlr t
+                prove --timer --formatter TAP::Formatter::JUnit -e ..\install\bin\raku -vlr t
               workingDirectory: '$(Pipeline.Workspace)/rakudo'
               enabled: ${{ ne( variant, 'relocatable' ) }}
               displayName: Test Rakudo (Windows)
@@ -565,7 +565,7 @@ stages:
                 pwd
                 ls -l .
                 $Env:PERL_TEST_HARNESS_DUMP_TAP = "test_results"
-                prove --formatter TAP::Formatter::JUnit -e ..\install-moved\bin\raku -vlr t
+                prove --timer --formatter TAP::Formatter::JUnit -e ..\install-moved\bin\raku -vlr t
               workingDirectory: '$(Pipeline.Workspace)/rakudo'
               enabled: ${{ eq( variant, 'relocatable' ) }}
               displayName: Test Rakudo (relocated, Windows)
@@ -604,14 +604,14 @@ stages:
             - script: |
                 pwd
                 ls -l .
-                env PERL_TEST_HARNESS_DUMP_TAP=test_results prove --formatter TAP::Formatter::JUnit  -j3 -e ../install/bin/raku -vlr t && echo "##vso[build.addbuildtag]moar-${{ os }}-${{ coalesce(variant, 'normal') }}-tests-clean"
+                env PERL_TEST_HARNESS_DUMP_TAP=test_results prove --timer --formatter TAP::Formatter::JUnit  -j3 -e ../install/bin/raku -vlr t && echo "##vso[build.addbuildtag]moar-${{ os }}-${{ coalesce(variant, 'normal') }}-tests-clean"
               workingDirectory: '$(Pipeline.Workspace)/rakudo'
               enabled: ${{ eq( variant, '' ) }}
               displayName: Test Rakudo
             - script: |
                 pwd
                 ls -l .
-                env PERL_TEST_HARNESS_DUMP_TAP=test_results prove --formatter TAP::Formatter::JUnit -j3 -e ../install-moved/bin/raku -vlr t && echo "##vso[build.addbuildtag]moar-${{ os }}-${{ coalesce(variant, 'normal') }}-tests-clean"
+                env PERL_TEST_HARNESS_DUMP_TAP=test_results prove --timer --formatter TAP::Formatter::JUnit -j3 -e ../install-moved/bin/raku -vlr t && echo "##vso[build.addbuildtag]moar-${{ os }}-${{ coalesce(variant, 'normal') }}-tests-clean"
               workingDirectory: '$(Pipeline.Workspace)/rakudo'
               enabled: ${{ eq( variant, 'relocatable' ) }}
               displayName: Test Rakudo (relocated)
@@ -755,6 +755,10 @@ stages:
         echo "creating test_results folder"
         mkdir test_results
 
+        echo "making spectest.data smaller"
+        cp t/spectest.data t/spectest.data.backup
+        head -n 150 t/spectest.data.backup > t/spectest.data
+
         export PERL_TEST_HARNESS_DUMP_TAP=test_results
         make --trace  TEST_JOBS=3 m-spectest
       workingDirectory: '$(Pipeline.Workspace)/rakudo'
@@ -763,7 +767,8 @@ stages:
     - script: |
         echo "listing test results subfolders"
         ls -lisah test_results/*
-        tap2junit test_results/**/*
+        echo "running tap2junit"
+        tap2junit --verbose test_results/**/* || echo "oh no, failed to convert!"
       workingDirectory: '$(Pipeline.Workspace)/rakudo'
       displayName: convert tap to junit
       condition: succeededOrFailed()
@@ -776,6 +781,14 @@ stages:
         searchFolder: '$(Pipeline.Workspace)/rakudo/test_results'
         testRunTitle: "full spectest with spesh NoDelay"
       condition: succeededOrFailed()
+
+    - task: PublishPipelineArtifact@1
+      displayName: publish test results files
+      condition: always()
+      inputs:
+        targetPath: $(Pipeline.Workspace)/rakudo/test_results
+        artifact: MVM_extra_moar_spesh_relocatable_test_results_Lin
+        publishLocation: 'pipeline'
 
 
 - stage: Build_Precomp_Release
