fix output dir for debugspam

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -307,17 +307,19 @@ stages:
                   INSP=$( [[ -e ../install ]] && echo "../install/bin" || echo "../install-moved/bin" )
                   echo "looking at files in $INSP"
 
-                  strace -fftt -o nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  strace -fftt -o debugspam/nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
                   ldd $INSP/nqp || echo "ldd nqp failed"
 
-                  strace -fftt -o rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  strace -fftt -o debugspam/rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
                   ldd $INSP/rakudo || echo "ldd rakudo failed"
 
                   ldd $INSP/moar || echo "ldd moar failed"
-                  ls -l debugspam/*strace*
-                  ls -l debugspam/*lddebug*
+                  echo "debugspam folder:"
+                  ls -l debugspam
+                  echo "this folder:"
+                  ls -l
                   echo "debug stuff done"
                 workingDirectory: '$(Pipeline.Workspace)/rakudo'
                 displayName: Grab a bunch of debug outputs for nqp and rakudo
@@ -533,8 +535,10 @@ stages:
                 ldd $INSP/rakudo || echo "ldd rakudo failed"
 
                 ldd $INSP/moar || echo "ldd moar failed"
-                ls -l debugspam/*strace*
-                ls -l debugspam/*lddebug*
+                echo "debugspam folder:"
+                ls -l debugspam
+                echo "this folder:"
+                ls -l
                 echo "debug stuff done"
               workingDirectory: '$(Pipeline.Workspace)/rakudo'
               displayName: Grab a bunch of debug outputs for nqp and rakudo
@@ -630,8 +634,10 @@ stages:
         ldd $INSP/rakudo || echo "ldd rakudo failed"
 
         ldd $INSP/moar || echo "ldd moar failed"
-        ls -l debugspam/*strace*
-        ls -l debugspam/*lddebug*
+        echo "debugspam folder:"
+        ls -l debugspam
+        echo "this folder:"
+        ls -l
         echo "debug stuff done"
       workingDirectory: '$(Pipeline.Workspace)/rakudo'
       displayName: Grab a bunch of debug outputs for nqp and rakudo
