put debugspam in a new artifact

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -304,15 +304,15 @@ stages:
                 displayName: Build Rakudo
               - script: |
                   echo "making a bunch of debug output"
-                  strace -fftt -o nqp-hello-strace.txt ../install/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt ../install/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                  ldd ../install/bin/nqp || echo "ldd nqp failed"
+                  strace -fftt -o nqp-hello-strace.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  ldd ../install*/bin/nqp || echo "ldd nqp failed"
 
-                  strace -fftt -o rakudo-hello-strace.txt ../install/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt ../install/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                  ldd ../install/bin/rakudo || echo "ldd rakudo failed"
+                  strace -fftt -o rakudo-hello-strace.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  ldd ../install*/bin/rakudo || echo "ldd rakudo failed"
 
-                  ldd ../install/bin/moar || echo "ldd moar failed"
+                  ldd ../install*/bin/moar || echo "ldd moar failed"
                   ls -l *strace*
                   ls -l *lddebug*
                   echo "debug stuff done"
@@ -516,21 +516,30 @@ stages:
 
           - ${{ if ne(os, 'Win') }}:
             - script: |
+                mkdir debugspam
+
                 echo "making a bunch of debug output"
-                strace -fftt -o nqp-hello-strace.txt ../install/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt ../install/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                ldd ../install/bin/nqp || echo "ldd nqp failed"
+                strace -fftt -o debugspam/nqp-hello-strace.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                ldd ../install*/bin/nqp || echo "ldd nqp failed"
 
-                strace -fftt -o rakudo-hello-strace.txt ../install/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt ../install/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                ldd ../install/bin/rakudo || echo "ldd rakudo failed"
+                strace -fftt -o debugspam/rakudo-hello-strace.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                ldd ../install*/bin/rakudo || echo "ldd rakudo failed"
 
-                ldd ../install/bin/moar || echo "ldd moar failed"
+                ldd ../install*/bin/moar || echo "ldd moar failed"
                 ls -l *strace*
                 ls -l *lddebug*
                 echo "debug stuff done"
               workingDirectory: '$(Pipeline.Workspace)/rakudo'
               displayName: Grab a bunch of debug outputs for nqp and rakudo
+
+            - task: PublishPipelineArtifact@1
+              displayName: publish debug logs
+              inputs:
+                targetPath: $(Pipeline.Workspace)/rakudo/debugspam
+                artifact: ${{ backend }}_debugspam_${{ coalesce(variant, 'normal') }}_${{ os }}
+                publishLocation: 'pipeline'
 
             - script: |
                 pwd
@@ -602,21 +611,30 @@ stages:
         ls -lisah ../install/include* ../install/include/*
         true
     - script: |
+        mkdir debugspam
+
         echo "making a bunch of debug output"
-        strace -fftt -o nqp-hello-strace.txt ../install/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt ../install/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-        ldd ../install/bin/nqp || echo "ldd nqp failed"
+        strace -fftt -o debugspam/nqp-hello-strace.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+        ldd ../install*/bin/nqp || echo "ldd nqp failed"
 
-        strace -fftt -o rakudo-hello-strace.txt ../install/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt ../install/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-        ldd ../install/bin/rakudo || echo "ldd rakudo failed"
+        strace -fftt -o debugspam/rakudo-hello-strace.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+        ldd ../install*/bin/rakudo || echo "ldd rakudo failed"
 
-        ldd ../install/bin/moar || echo "ldd moar failed"
+        ldd ../install*/bin/moar || echo "ldd moar failed"
         ls -l *strace*
         ls -l *lddebug*
         echo "debug stuff done"
       workingDirectory: '$(Pipeline.Workspace)/rakudo'
       displayName: Grab a bunch of debug outputs for nqp and rakudo
+
+    - task: PublishPipelineArtifact@1
+      displayName: publish debug logs
+      inputs:
+        targetPath: $(Pipeline.Workspace)/rakudo/debugspam
+        artifact: MVM_debugspam_extraspesh_relocatable_Lin
+        publishLocation: 'pipeline'
 
     - script: |
         make
