try to put debugspam from different jobs/stages together

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -313,15 +313,17 @@ stages:
                 displayName: Build Rakudo
               - script: |
                   echo "making a bunch of debug output"
+                  mkdir debugspam
+
                   INSP=$( [[ -e ../install ]] && echo "../install/bin" || echo "../install-moved/bin" )
                   echo "looking at files in $INSP"
 
-                  strace -fftt -o debugspam/nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  strace -fftt -o debugspam/$(Agent.JobName)-nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/$(Agent.JobName)-nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
                   ldd $INSP/nqp || echo "ldd nqp failed"
 
-                  strace -fftt -o debugspam/rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  strace -fftt -o debugspam/$(Agent.JobName)-rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/$(Agent.JobName)-rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
                   ldd $INSP/rakudo || echo "ldd rakudo failed"
 
                   ldd $INSP/moar || echo "ldd moar failed"
@@ -332,7 +334,13 @@ stages:
                   echo "debug stuff done"
                 workingDirectory: '$(Pipeline.Workspace)/rakudo'
                 displayName: Grab a bunch of debug outputs for nqp and rakudo
- 
+              - task: PublishPipelineArtifact@1
+                displayName: publish debug logs
+                inputs:
+                  targetPath: $(Pipeline.Workspace)/rakudo/debugspam
+                  artifact: ${{ backend }}_${{ coalesce(variant, 'normal') }}_debugspam_${{ os }}
+                  publishLocation: 'pipeline'
+
             - ${{ if eq(os, 'Win') }}:
               - pwsh: |
                   ${{ variables.PWSH_DEV }}
@@ -535,12 +543,12 @@ stages:
                 echo "looking at files in $INSP"
 
                 echo "making a bunch of debug output"
-                strace -fftt -o debugspam/nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                strace -fftt -o debugspam/$(Agent.JobName)-nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/$(Agent.JobName)-nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
                 ldd $INSP/nqp || echo "ldd nqp failed"
 
-                strace -fftt -o debugspam/rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                strace -fftt -o debugspam/$(Agent.JobName)-rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/$(Agent.JobName)-rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
                 ldd $INSP/rakudo || echo "ldd rakudo failed"
 
                 ldd $INSP/moar || echo "ldd moar failed"
@@ -634,12 +642,12 @@ stages:
         INSP=$( [[ -e ../install ]] && echo "../install/bin" || echo "../install-moved/bin" )
 
         echo "making a bunch of debug output"
-        strace -fftt -o debugspam/nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+        strace -fftt -o debugspam/$(Agent.JobName)-nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/$(Agent.JobName)-nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
         ldd $INSP/nqp || echo "ldd nqp failed"
 
-        strace -fftt -o debugspam/rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+        strace -fftt -o debugspam/$(Agent.JobName)-rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/$(Agent.JobName)-rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
         ldd $INSP/rakudo || echo "ldd rakudo failed"
 
         ldd $INSP/moar || echo "ldd moar failed"
@@ -655,7 +663,7 @@ stages:
       displayName: publish debug logs
       inputs:
         targetPath: $(Pipeline.Workspace)/rakudo/debugspam
-        artifact: MVM_debugspam_extraspesh_relocatable_Lin
+        artifact: MVM_relocatable_debugspam_Lin
         publishLocation: 'pipeline'
 
     - script: |
