look at only one, correct, path for debugspam

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -304,15 +304,18 @@ stages:
                 displayName: Build Rakudo
               - script: |
                   echo "making a bunch of debug output"
-                  strace -fftt -o nqp-hello-strace.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                  ldd ../install*/bin/nqp || echo "ldd nqp failed"
+                  INSP=$( [[ -e ../install ]] && echo "../install/bin" || echo "../install-moved/bin" )
+                  echo "looking at files in $INSP"
 
-                  strace -fftt -o rakudo-hello-strace.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                  ldd ../install*/bin/rakudo || echo "ldd rakudo failed"
+                  strace -fftt -o nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                  ldd $INSP/nqp || echo "ldd nqp failed"
 
-                  ldd ../install*/bin/moar || echo "ldd moar failed"
+                  strace -fftt -o rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                  ldd $INSP/rakudo || echo "ldd rakudo failed"
+
+                  ldd $INSP/moar || echo "ldd moar failed"
                   ls -l *strace*
                   ls -l *lddebug*
                   echo "debug stuff done"
@@ -517,17 +520,19 @@ stages:
           - ${{ if ne(os, 'Win') }}:
             - script: |
                 mkdir debugspam
+                INSP=$( [[ -e ../install ]] && echo "../install/bin" || echo "../install-moved/bin" )
+                echo "looking at files in $INSP"
 
                 echo "making a bunch of debug output"
-                strace -fftt -o debugspam/nqp-hello-strace.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-                ldd ../install*/bin/nqp || echo "ldd nqp failed"
+                strace -fftt -o debugspam/nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+                ldd $INSP/bin/nqp || echo "ldd nqp failed"
 
-                strace -fftt -o debugspam/rakudo-hello-strace.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-                ldd ../install*/bin/rakudo || echo "ldd rakudo failed"
+                strace -fftt -o debugspam/rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+                ldd $INSP/rakudo || echo "ldd rakudo failed"
 
-                ldd ../install*/bin/moar || echo "ldd moar failed"
+                ldd $INSP/moar || echo "ldd moar failed"
                 ls -l *strace*
                 ls -l *lddebug*
                 echo "debug stuff done"
@@ -613,16 +618,18 @@ stages:
     - script: |
         mkdir debugspam
 
+        INSP=$( [[ -e ../install ]] && echo "../install/bin" || echo "../install-moved/bin" )
+
         echo "making a bunch of debug output"
-        strace -fftt -o debugspam/nqp-hello-strace.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt ../install*/bin/nqp -e 'say("hi")' || echo "nqp hello strace failed"
-        ldd ../install*/bin/nqp || echo "ldd nqp failed"
+        strace -fftt -o debugspam/nqp-hello-strace.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/nqp-hello-lddebug.txt $INSP/nqp -e 'say("hi")' || echo "nqp hello strace failed"
+        ldd $INSP/nqp || echo "ldd nqp failed"
 
-        strace -fftt -o debugspam/rakudo-hello-strace.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt ../install*/bin/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
-        ldd ../install*/bin/rakudo || echo "ldd rakudo failed"
+        strace -fftt -o debugspam/rakudo-hello-strace.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+        env LD_DEBUG=files,libs,versions LD_DEBUG_OUTPUT=debugspam/rakudo-hello-lddebug.txt $INSP/rakudo -e 'say("hi")' || echo "rakudo hello strace failed"
+        ldd $INSP/rakudo || echo "ldd rakudo failed"
 
-        ldd ../install*/bin/moar || echo "ldd moar failed"
+        ldd $INSP/moar || echo "ldd moar failed"
         ls -l *strace*
         ls -l *lddebug*
         echo "debug stuff done"
